### ISSUE TITLE
how to use it without composer?

### ISSUE THREAD

**Issue by mrbbp** [sixlive/parsedown-highlight#8]
Sorry for this newb question i use parsedown like this
```php
  require_once 'libs/Parsedown.php';
  require_once 'libs/ParsedownExtra.php';
// is it good?
  require_once 'libs/ParsedownHighlight.php';
  // récupère le nom du ficier dans l'url
  $fichier = $_GET['f'];
  // ouvre le fichier md
  $my_text = file_get_contents($fichier, true);
        // does not work! what i've missed?
        //$Extra = new ParsedownHighlight();
  $Extra = new ParsedownExtra();
  echo $result = $Extra->text($my_text);
```
but i'm unable to use your lib... i'm doing something wrong but i don't know what!
Pleaz help!

**Comment by sixlive** [comment]
I don’t think this is compatible with parsedown extra at the moment.

To highlight though you would use `new ParsedownHighlight` rather than `new ParsedownExtra`.

**Comment by mrbbp** [comment]
i remove parseDownExtra and use `$Extra = new ParsedownHighlight();`
i've got an error on this line.
am i making mistake?

any idea?
i use the 1.8 beta7 parseDown branch.
```php
  require_once 'libs/Parsedown.php';
  require_once 'libs/ParsedownHighlight.php';
  $fichier = $_GET['f'];
  $my_text = file_get_contents($fichier, true);
  $Extra = new ParsedownHighlight();
  echo $result = $Extra->text($my_text);
```

**Comment by sixlive** [comment]
Its not finding the ParedownHighlight library in the `libs` directory.

**Comment by mrbbp** [comment]
it's there!
<img width="267" alt="Capture d’écran 2020-04-15 à 00 26 45" src="https://user-images.githubusercontent.com/1716290/79280118-dc61e080-7eaf-11ea-9900-6c8d856689f8.png">
