### ISSUE TITLE
Add possibility to use parsedown-highlight with parsedown-extra

### ISSUE THREAD

**Issue by Arteneko** [sixlive/parsedown-highlight#9]
As title suggests. By design, parsedown's extensions are made by inheritance, which means that since you inherit Parsedown, parsedown-extra cannot be used.

**Comment by sixlive** [comment]
Does this address your needs? https://github.com/sixlive/parsedown-highlight/pull/10

**Comment by Arteneko** [comment]
That should, indeed, do the trick.

**Comment by sixlive** [comment]
I really wish it had a plugin system, operating on inheritance is a drag.

**Comment by Arteneko** [comment]
Indeed, that's a shame. Parsedown would require a major version to be able to break free from historical code and provide a newer, cleaner API

**Comment by sixlive** [comment]
Yup. Tagged in [v0.4.0](https://github.com/sixlive/parsedown-highlight/releases/tag/v0.4.0)
